version: '3.8'

services:
  # База даних MySQL
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dimamuzik228
      MYSQL_DATABASE: data_for_web
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      
  # Frontend (Blazor)
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    depends_on:
      - api
    ports:
      - "8081:80"

  # Backend API (.NET)
  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    container_name: dotnet_api
    restart: on-failure
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=data_for_web;Uid=root;Pwd=dimamuzik228;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "7079:8080"

volumes:
  db_data:  api-1:
    image: api-1
    build:
      context: .
      dockerfile: Api/Dockerfile

